### ISSUE TITLE
Underglow in reply cars

### ISSUE THREAD

**Issue by AbdullahUQU** [Martinii89/ReplayManipulatorOpenSource#7]
I need to add Underglow effect in reply cars and that existed in AlphaConsole 
![Rocket League Screenshot 2023 07 17 - 15 04 36 81](https://github.com/Martinii89/ReplayManipulatorOpenSource/assets/112553702/668fcca4-1111-49df-bb41-a0115451646a)

**Comment by Martinii89** [comment]
This is not possible with the pluginsdk, you'd need a closed source plugin using a different sdk to do this. Closing this as it wouldn't be possible to do.

**Comment by AbdullahUQU** [comment]
So? What is the solution?

**Comment by Martinii89** [comment]
The solution is to convince someone (not me) to make to make a plugin with such a feature
